version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: jejevkin/foodgram_project:latest
    restart: always
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6-alpine
    depends_on:
      - web
    ports:
      - 80:80
#      - 403:403
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - static_volume:/code/static/
      - media_volume:/code/media/
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always

#  certbot:
#    image: certbot/certbot
#    depends_on:
#      - web
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
